n = input('digite alguma coisa:')
print('o tipo primitivo é desse valor é:', type(n))
print('so tem espacos?', n.isspace())
print('é um numero?', n.isnumeric())
print('é alfabetico?', n.isalpha())
print('é alfanumerico?', n.isalnum())
print('esta em maisculo?', n.isupper())
print('esta em minusculo?', n.islower())
print('esta capitalizado?', n.istitle())
